#!/bin/bash

modified_files=$(git diff --name-only $1 $2)
docker_id=$(docker-compose ps -q php) # Replace php by docker's service name

function has_changed() {
    echo "Checking if $1 has changed since last time"
    echo ${modified_files} | grep -q $1 && eval "$2"
}

if [[ $(docker inspect -f '{{.State.Running}}' "${docker_id}") = false ]]; then
    echo "${docker_id} is not running, skipping hook"
    exit 0
fi

# Edit with your configuration
if [[ -f hooks/conf.txt ]]; then
    config=$(cat hooks/conf.txt)
else
    config="dev"
fi

has_changed hooks/ "echo 'Changes found, copying hooks/ to .git/hooks' && docker exec -t "${docker_id}" yarn hooks" || echo "No change found"

has_changed package.json "echo 'Changes found, running yarn install' && docker exec -t "${docker_id}" yarn install" || echo "No change found"

# Change the directory to where your javascript and sass files are to run webpack
if has_changed templates/ ; then
    echo "Running script ${config}" && docker exec -d "${docker_id}" yarn "${config}"
else
    echo "No change found"
    if [[ "$config" == "watch" ]]; then
        echo "Starting detached watch mode"
        docker exec -d "${docker_id}" yarn "${config}"
    fi
fi

echo 'Successfully checked-out'
