#!/bin/bash

modified_files=$(git diff --cached --name-only)
docker_id=$(docker-compose ps -q php) # Replace php by docker's service name
branchs_list=$(git branch -r)

function has_changed() {
    echo "Checking if $1 has changed"
    echo ${modified_files} | grep -q $1 && eval "$2"
}

if [[ $(docker inspect -f '{{.State.Running}}' "${docker_id}") = false ]]; then
    echo "${docker_id} is not running, skipping hook"
    exit 0
fi

has_changed hooks/ "echo 'Changes found, copying hooks/ to .git/hooks' docker exec -t "${docker_id}" yarn hooks" || echo "No change found"

echo "Checking if there is any dependabot branch"
if [[ ${branchs_list} == *"dependabot/npm_and_yarn/"* ]]; then
    echo "New dependabot branch found; please run 'yarn upgrade --latest'"
else
    echo 'No dependabot branch found'
fi

echo 'Successfully committed'
